### ISSUE TITLE
Error when implementing custom keyword

### ISSUE THREAD

**Issue by nvnieuwk** [harrel56/json-schema#123]
Hi, thanks for making this awesome library!

I'm currently implementing a custom keyword alongside some custom formats and am running into this error: 
```
dev.harrel.jsonschema.MetaSchemaResolvingException: Parsing meta-schema [https://json-schema.org/draft/2020-12/schema] failed
	at dev.harrel.jsonschema.MetaSchemaResolvingException.parsingFailure(MetaSchemaResolvingException.java:19)
	at dev.harrel.jsonschema.MetaSchemaValidator$DefaultMetaSchemaValidator.resolveExternalSchema(MetaSchemaValidator.java:92)
	at dev.harrel.jsonschema.MetaSchemaValidator$DefaultMetaSchemaValidator.lambda$resolveMetaSchema$4(MetaSchemaValidator.java:77)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at dev.harrel.jsonschema.MetaSchemaValidator$DefaultMetaSchemaValidator.resolveMetaSchema(MetaSchemaValidator.java:77)
	at dev.harrel.jsonschema.MetaSchemaValidator$DefaultMetaSchemaValidator.validateSchema(MetaSchemaValidator.java:45)
	at dev.harrel.jsonschema.JsonParser.validateAgainstMetaSchema(JsonParser.java:153)
	at dev.harrel.jsonschema.JsonParser.parseRootSchemaInternal(JsonParser.java:58)
	at dev.harrel.jsonschema.JsonParser.parseRootSchema(JsonParser.java:29)
	at dev.harrel.jsonschema.Validator.registerSchema(Validator.java:75)
	at dev.harrel.jsonschema.ValidatorFactory.validate(ValidatorFactory.java:230)
	at dev.harrel.jsonschema.ValidatorFactory.validate(ValidatorFactory.java:198)
```

My custom EvaluatorFactory looks like this:

```groovy
class CustomEvaluatorFactory implements EvaluatorFactory {
    @Override
    public Optional<Evaluator> create(SchemaParsingContext ctx, String fieldName, JsonNode schemaNode) {
        // Format evaluators
        if (fieldName == "format" && schemaNode.isString()) {
            def String schemaString = schemaNode.asString()
            switch (schemaString) {
                case "directory-path":
                return Optional.of(new FormatDirectoryPathEvaluator())
                case "file-path":
                return Optional.of(new FormatFilePathEvaluator())
                case "path":
                return Optional.of(new FormatPathEvaluator())
                case "file-path-pattern":
                return Optional.of(new FormatFilePathPatternEvaluator())
            }
        } 
        else if (fieldName == "exists" && schemaNode.isBoolean() {
            return Optional.of(new ExistsEvaluator(schemaNode.asBoolean()))
        })
        return Optional.empty();
    }
}
```

The code for the custom formats worked perfectly, but I'm encountering the above error when adding the `exists` keyword and I'm not sure how to fix this. Would you happen to know what could be going wrong?

Thanks!
-Nicolas

**Comment by harrel56** [comment]
> I misplaced a bracket in my last if statement, it works now 😁

I was looking into it briefly on my phone earlier today but couldn't really tell what could be causing this - glad that it turned out to be just a typo!
